Style/BracesAroundHashParameters:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/LineLength:
    Max: 120
Layout/IndentHash:
    Enabled: false
Metrics/MethodLength:
    Max: 60
